### ISSUE TITLE
slime C-c C-c does not check a define-test form

### ISSUE THREAD

**Issue by jimka2001** [OdonataResearchLLC/lisp-unit#30]
I've created PR fix-for-slime which changes the macro expansion such that C-c C-c can
check and annotate the define-test form.

**Comment by ThomasHermann** [comment]
Implemented this in a slightly different way, it's in the develop branch. Didn't save the thunk and added some logic so that checking the form is optional.

**Comment by jimka2001** [comment]
Hi Thomas, does C-c C-c check the form or not by default?  Does the user have to do something special to have the form checked, or does the user have to do something special to prevent the form from being checked?

**Comment by ThomasHermann** [comment]
It is off by default, added a function `check-code` to enable the checking. Should have mentioned that, it will make it into the documentation. I'm trying to get a 1.0 release out by the end of the year and the documentation will be updated with the release.

**Comment by jimka2001** [comment]
Why would you want it off by default? What's the motivation for that?

**Comment by rtoy** [comment]
If this means that C-c C-c in slime defines the test and also runs it, then I think I'd like it off.  C-c C-c is called slime-compiled-defun, not slime-compile-defun-and-execute.

**Comment by jimka2001** [comment]
My intention was that c-c c-c not run the function but define the test and
issue compiler warnings of the code analogous to c-c c-c in a defun or
defmethod or defclass.

On the other hand, having some key other bind key to define the test and
run it would be great also.

**Comment by rtoy** [comment]
My apologies.  I misinterpreted what "check" meant.  C-c C-c seems to define the test and compile it for me with a recent lisp-unit.

**Comment by ThomasHermann** [comment]
Off by default because I'm more interested in developing code than in developing unit tests. My rationale is that it is turned when you are developing the unit tests, but you don't want it turned on when you are running the tests to check code development. Ideally, you are spending most of your time developing code.

Another reason it is off by default is that my primary development environment is LispWorks, not slime, so it is a feature that I don't usually use.

**Comment by jimka2001** [comment]
But having it on by default would not cause it to be checked when running,
would it? Why would it?  The edit that I made, only made it checkable
during compilation of the define-test form, not during the run of the tests.

On Sun, Dec 20, 2015 at 8:41 PM, Thomas M. Hermann <notifications@github.com

**Comment by ThomasHermann** [comment]
Correct, that's the same case for the way I implemented it. I'm conflating defining and running the tests. Still, I have a problem with generating a function that is only used to provide feedback to an IDE. It seems like unnecessary work. I appreciate why it is useful for SLIME, but it didn't seem correct to have it done by default.

Is there a reliable way to recognize that the test is being defined in SLIME? That would be the correct way to do it.

**Comment by jimka2001** [comment]
As I’m not a lispworks user please explain this confusion to me.

When I define a test case and I, for example, call a function with the wrong number of arguments,
and when I define a function (via defun) and call the same function with the same wrong number of arguments,
I would like a warning on both at definition time.

How is this different in lispworks?
And how does your implementation treat these differently?

Assuming lispworks does not warn you when you define a function with defun, why can you make lispworks treat define-test the same way?

Jim

**Comment by ThomasHermann** [comment]
Getting this to work with LispWorks will require a little more effort. LW gives you the option of addressing the condition immediately or moving on. If you want to address it immediately, a conditions browser window is opened that allows you to work through all of the conditions.

I think this feature will be implementation specific and depend on details of how evaluation and compilation are performed.

I was just getting it to work for SLIME, more general interaction with the IDE/implementaiton will take a little effort to understand what is required.

**Comment by jimka2001** [comment]
Hmm, now I'm confused.  The code I submitted worked fine in slime.  
C-c C-c compiles and evals the top level form.  I just modified the macro expansion
which previously had a quoted form of code, which of course compiles and evaluates
as a quoted list.  I changed it to also contain a thunk, which evaluates with no side effect
but the compilation of which works exactly the same as any other top level form containing
a thunk.

Did you find a problem with it?   I was saving the thunk in the lisp-unit data structure, but that's not
really necessary.

**Comment by ThomasHermann** [comment]
The original code you submitted didn't work with tags. I need to think about this a little more.

**Comment by ThomasHermann** [comment]
lisp-unit2 handles this. I'll go look at what they did.

**Comment by jimka2001** [comment]
tags?  is this a feature of lisp-unit that I am missing?  sounds
interesting.

**Comment by ThomasHermann** [comment]
https://github.com/OdonataResearchLLC/lisp-unit/wiki#how-to-organize-tests-with-tags

**Comment by jimka2001** [comment]
Ahh, I didn't know about tags.  I'll have to check it out. Great that you
caught the bug that I introduced.
BTW did you catch the bug by running the unit tests of the lisp-unit
package?

**Comment by jimka2001** [comment]
Mentioned above, it would be very nice to have a slime bind-key to run the test defined by the current defun, or run all the tests defined in the current file.

To run the "current" test, I'd have to parse the define-test to get the test form (that's easy), and then eval the lisp expression --> (run-tests '(THE-TEST) THE-PACKAGE-SYMBOL)
I'm not sure how to calculate THE-PACKAGE-SYMBOL.  Perhaps it is simply the package name of the package of THE-TEST?

I didn't find a lisp-unit function to run just a single test.   Should I add one? along with the slime code?
