### ISSUE TITLE
Defining tests with gensymmed names?

### ISSUE THREAD

**Issue by rebcabin** [OdonataResearchLLC/lisp-unit#31]
I discovered that I cannot define tests with gensymmed names in a macro form. Please see the following gist https://gist.github.com/rebcabin/0c550e2373f4f7e3f65c, in which I show that I can define functions with gensymmed names, but not tests.  This may be a known and acceptable limitation, but I was surprised by it and wasn't able to predict from the documentation that it would not work.  If it's an intentional limitation, perhaps a note to the wise in the documentation would help?

**Comment by ThomasHermann** [comment]
This is an internal limitation. The first line in the wiki reference for `define-test` is

> This macro defines a test called `name` with the expressions specified, in the package
>  specified by the value of *package* in effect when define-test is executed.

A gensym is uninterned, so it is impossible for it to be defined in the package or any package. An example that is more analogous to the function example `M1` would be:

```common-lisp
LISP-UNIT 44 > (defmacro m2 ()
                 (let ((g (gensym)))
                   `(progn
                      (define-test ,g
                        (format t "my name is ~A~%" ',g))
                      (run-tests (list ,g)))))
M2

LISP-UNIT 45 > (m2)

Error: The variable #:G1914 is unbound.
  1 (continue) Try evaluating #:G1914 again.
  2 Specify a value to use this time instead of evaluating #:G1914.
  3 Specify a value to set #:G1914 to.
  4 (abort) Return to level 0.
  5 Return to top loop level 0.

Type :b for backtrace or :c <option number> to proceed.
Type :bug-form "<subject>" for a bug report template or :? for other options.

LISP-UNIT 46 : 1 > 
```

An approach that might work would be to use `GENTEMP`. I'm only guessing at what your use case is, so if that isn't it and there is a new feature that would be useful here, please explain it.
